require('base/tabs')
require('base/previmoff')
require('plugins/plugin_manager')
require('plugins/themes/theme_selector')
require('plugins/tree_sitter')
require('plugins/lsp_zero')
require('plugins/cmake')
require('plugins/cpp_debug')
require('plugins/dap_ui')
require('keys/key(re)maps')

